[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.19'

[fmt]
line_length = 120

[doc]
offline = true

[install]
auto_detect = true

[remappings]
'@chainlink/contracts-ccip=node_modules/@chainlink/contracts-ccip'